<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Prashant_Laptop" failures="2" tests="2" name="Test(failed)" time="0.086" errors="0" timestamp="2024-10-25T16:15:58 IST">
  <testcase classname="reRunTestCases.TestCases" name="method1" time="0.018">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at reRunTestCases.TestCases.method1(TestCases.java:9)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- method1 -->
  <testcase classname="reRunTestCases.TestCases" name="method2" time="0.001">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at reRunTestCases.TestCases.method2(TestCases.java:13)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- method2 -->
  <testcase classname="reRunTestCases.TestCases" name="method3" time="0.0">
    <ignored/>
  </testcase> <!-- method3 -->
</testsuite> <!-- Test(failed) -->
